[package]
name = "hooya"
version = "0.1.0"
edition = "2021"
authors = [ "wesl-ee <w@wesl.ee>" ]

[dependencies]
tonic = { version = "0.9" }
prost = { version = "0.11" }
cid = "0.10"
ring = "0.16"
tokio = { version = "1.0", features = [ "macros", "rt-multi-thread"] }
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls" ] }
anyhow = "1.0"
infer = "0.14"
futures-util = "0.3"
image = "0.24"
kamadak-exif = "0.5"

[build-dependencies]
tonic-build = "0.9"
