[package]
name = "hooya"
version = "0.1.0"
edition = "2021"
authors = [ "wesl-ee <w@wesl.ee>" ]

[dependencies]
tonic = { version = "0.9" }
prost = { version = "0.11" }
cid = "0.10"
ring = "0.16"
tokio = { version = "1.0", features = [ "macros", "rt-multi-thread"] }
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls" ] }
anyhow = "1.0"
# TODO
# I should parse file content myself. Only handling a few distinct mimetypes and
# this crate is way old
tree_magic = "0.2.3"

[build-dependencies]
tonic-build = "0.9"
