[package]
name = "hooyad"
version = "0.1.2"
edition = "2021"
authors = ["wesl-ee <w@wesl.ee>"]

[[bin]]
name = "hooyad"
path = "src/main.rs"

[dependencies]
tonic = { version = "0.11", features = ["transport"] }
prost = { version = "0.12" }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread", "fs", "io-util"] }
tokio-stream = { version = "0.1", features = ["sync"] }
hooya = { path = "../../packages/hooya" }
hooya-config = { path = "../../packages/hooya-config" }
semver = "1.0"
clap = { version = "4.3", features = ["env", "cargo"] }
sqlx = { version = "0.6", features = ["sqlite", "runtime-tokio-native-tls"] }
anyhow = "1.0"
futures-util = "0.3"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15"
rand = "0.8"
num_cpus = "1.0"
libp2p = { version = "0.53", features = ["gossipsub", "identify", "ping", "tcp", "tokio", "macros", "dns", "mdns", "noise", "yamux"] }
discv5 = "0.4"
enr = "0.10"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }